# Generated by Django 3.0.5 on 2020-05-16 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='Никнейм')),
                ('password', models.CharField(max_length=20, verbose_name='Пароль')),
                ('note_amount', models.IntegerField(verbose_name='Кол-во заметок')),
                ('last_online', models.DateTimeField(verbose_name='Последний раз в сети')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=30, verbose_name='Тема заметки')),
                ('text', models.TextField(max_length=404, verbose_name='Текст заметки')),
                ('date', models.DateTimeField(verbose_name='Дата создания')),
                ('last_edit', models.DateTimeField(verbose_name='Дата ласт изменения')),
                ('last_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web2app.User')),
            ],
        ),
    ]
