# Generated by Django 3.0.5 on 2020-05-16 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web2app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='note_amount',
            field=models.IntegerField(default=0, verbose_name='Кол-во заметок'),
        ),
    ]
