# Generated by Django 3.0.5 on 2020-05-23 11:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('web2app', '0002_auto_20200517_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin',
            field=models.BooleanField(default=False, verbose_name='Админка'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_online',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 23, 11, 42, 25, 946970, tzinfo=utc), verbose_name='Последний раз в сети'),
        ),
    ]
